---
- name: Create user account
  sudo: yes
  user: name='{{ dbuser }}'
        state=present

- name: Create empty repo directory
  sudo: yes
  file: path='{{ project }}' state=directory owner='{{ dbuser }}' mode=0755
