---
- name: Install PostgreSQL
  apt: pkg={{ item }}
       state=present
       update_cache=yes
  sudo: yes
  with_items:
    - libpq-dev
    - python-dev
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Create database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name='{{ dbname }}'
                 encoding='UTF-8'
                 lc_collate='en_GB.utf8'
                 lc_ctype='en_GB.utf8'
                 template='template0'

- name: Add database user
  sudo: yes
  sudo_user: postgres
  postgresql_user: db='{{ dbname }}'
                   name='{{ dbuser }}'
                   password='{{ dbpassword }}'
                   priv='CONNECT/ALL'
                   state=present

- name: Install psycopg2
  sudo: yes
  pip: name=psycopg2
       state=present
       virtualenv='{{ virtualenv }}'
