#!/bin/bash
source {{ virtualenv }}bin/activate
export DATABASE_NAME={{ dbname }}
export DATABASE_USER={{ dbuser }}
export DATABASE_PASSWORD={{ dbpassword }}
export DATABASE_HOST={{ dbhost }}
export DATABASE_PORT={{ dbport }}
export STATIC_ROOT={{ static }}
export MEDIA_ROOT={{ media }}
export SECRET_KEY="{{ key }}"
export TWITTER_KEY={{ twitter_key }}
export TWITTER_SECRET={{ twitter_secret }}
export DOMAIN={{ domain }}
python {{ project }}manage.py $@
