---

- name: Install Git
  apt: pkg=git state=present update_cache=yes
  sudo: yes

- name: Checkout project
  sudo: yes
  sudo_user: '{{ dbuser }}'
  git: repo='{{ repo }}' dest='{{ project }}' accept_hostkey=yes
  tags:
  - git
